# Generated by Django 5.2.3 on 2025-06-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='news',
            name='news_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='category_name',
            field=models.CharField(max_length=128),
        ),
    ]
