# Generated by Django 5.2.3 on 2025-07-02 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_news_options_alter_newscategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_favourites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.news')),
            ],
            options={
                'verbose_name_plural': 'Избранные',
            },
        ),
    ]
